spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
     url: jdbc:h2:mem:testdb
     username: sa
     password:
     initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

