server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keyloak-server:9000/auth/realms/demo/protocol/openid-connect/certs
          issuer-uri: http://keyloak-server:9000/auth/realms/demo
