spring:
  batch:
    job:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost/batch2
    username: postgres
    password: qqq
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true