spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
     url: jdbc:h2:mem:testdb
     username: sa
     password:
     initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
