spring:
  datasource:
     url: jdbc:h2:mem:testdb
     username: sa
     password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.springframework.jdbc.core: TRACE