spring:
  datasource:
    url: jdbc:postgresql://localhost/mydb

    username: postgres
    password: qqq

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true